# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hyunjoon Park
title: Computer Vision Researcher
email: hyunjoonpark0803@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  hjpark83
instagram_username: hjpark_83
linkedin_username: hyunjoon83
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hyunjoon Park and I'm researching in the field of Computer Vision \
  Currently, I am pursuing a Master's (MS) degree in Computer Software Engineering at Hanyang University. \
  I am a member of <a href="https://sites.google.com/view/hyu-cv">HYU CVLab</a> at Hanyang University, under the supervision of <a href="https://scholar.google.com/citations?user=zj-NER4AAAAJ&hl=en">Prof. Donghyeon Cho</a>

  **Research Interests:**
  - 3D Vision (3D Gaussian Splatting)
  - 3D Human Reconstruction
  - Generative Models

  **Office**: Room 503, IT/BT Building, 222, Wangsimni-ro, Seongdong-gu, Seoul, 04763, Korea. <a href="https://maps.google.com/?q=37.5559722,127.0492778" target="_blank" title="View on Google Maps"><i class="fas fa-map-marker-alt"></i></a>

# News items (displayed latest first)
news_items:
  - date: "2026-04"
    content: "First International Conference Publication! Paper accepted to **ICPR 2026** (International Conference on Pattern Recognition) and will be presented at the conference"
  - date: "2026-02"
    content: "Paper accepted to **IPIU 2026** (38th Workshop on Image Processing and Image Understanding) and presented poster at the conference"
  - date: "2025-09"
    content: "Start Master's degree at HYU CVLab under the supervision of Prof. Donghyeon Cho"
  - date: "2025-08"
    content: "Completed Bachelor's degree in Computer Software Engineering at Hanyang University"
  - date: "2025-02"
    content: "Paper accepted to **IPIU 2025** (37th Workshop on Image Processing and Image Understanding) and presented poster at the conference"
  - date: "2024-07"
    content: "Start undergraduate internship at HYU CVLab under the supervision of Prof. Donghyeon Cho"

content:
  - title: Publications # Title for the section
    layout: card # Type of content section (card layout)
    content:
      - title: Consistent Scene Understanding in 3D Gaussian Splatting via Multi-Cue Mask Refinement
        authors: <strong style="color:#1a73e8;">Hyunjoon Park</strong>, Donghyeon Cho
        venue: _ICPR 2026_ (28th International Conference on Pattern Recognition)
        image: images/icpr26.png
        link: https://icpr2026.org/
        link_text: Site
        badges:
          - text: International
            type: international
          - text: Conference
            type: conference
          - text: Poster
            type: poster
        abstract: |
          Reliable instance-level scene understanding is a fundamental prerequisite for object-level interactions and high-fidelity 3D representations.
          While current methods often leverage 2D foundation models, such as the Segment Anything Model (SAM), to obtain these priors, 2D centric design of SAM typically yields fragmented masks and inconsistent predictions across different views. 
          To address these issues, we propose a multi-cue mask refinement framework that produces consistent 2D instance masks to guide the optimization of 3D Gaussian Splatting (3DGS) feature fields.
          Our framework consists of three main stages. (1) A Multi-Cue Extraction that generates synergistic semantic, geometric, and structural priors from input images. 
          (2) A Multi-Cue-Guided Mask Merging process that consolidates fragmented masks using a composite merge score derived from semantic, depth, and edge cues. 
          (3) A Cross-View Mask Matching that establishes globally consistent identity assignments across all viewpoints. 
          By transforming viewpoint-specific segments into coherent 3D primitives, our approach enables stable 3D instance segmentation and effective downstream editing tasks. 
          Experiments demonstrate that our method significantly improves cross-view consistency and segmentation stability over existing baselines while maintaining high-fidelity photometric reconstruction.
        bibtex: |


      - title: 3DGS에서 2D SAM을 활용할 때 발생하는 한계점 극복 및 효과적인 3차원 공간 이해를 위한 방법에 관한 연구
        authors: <strong style="color:#1a73e8;">Hyunjoon Park</strong>, Donghyeon Cho
        venue: _IPIU 2026_ (38th Workshop on Image Processing and Image Understanding)
        image: images/ipiu26.png
        link: http://www.ipiu.or.kr/
        link_text: Site
        badges:
          - text: Domestic
            type: domestic
          - text: Workshop
            type: workshop
          - text: Poster
            type: poster
        abstract: |
          본 연구에서는 3D Gaussian Splatting(3DGS) 환경에서 2D Foundation Model인 SAM을 활용할 때 발생하는 과분할(Over-segmentation) 및 시점 간 불일치 문제(View-Inconsistency)를 해결하기 위한 프레임워크를 제안하고자 한다.
          SAM의 보수적인 경계 인식으로 인해 발생하는 파편화된 마스크 문제를 극복하기 위해, 본 연구는 DINOv2의 semantic embedding, LoG(Laplacian-of-Gaussian) edge detection, 그리고 DepthAnythingv2의 monocular depth estimation을 결합한 2단계 refinement pipeline을 구축하였다.
          먼저, 1단계에서는 깊이 기반의 제약을 두어 잘못된 마스크 병합을 억제한 뒤 두 개의 후보군들의 semantic, edge, depth 정보의 가중합을 임계값과 비교하여 병합여부를 결정하였다.
          그 다음으로 2단계에서는 시점 간 특징 유사도 클러스터링을 통해 전역적으로 일관된 객체 특성과 아이덴티티를 확립하고자 하였다.
          이를 통해 기존 3DGS의 렌더링 품질을 유지하면서도, 시점 변화에 강건한 객체 제거 및 인페인팅 등 정교한 3D Scene Editing 기능을 실현할 수 있도록 정확성과 효율성을 높일 수 있었다.
        bibtex: |
          @inproceedings{park2026sam3dgs,
            author    = {Hyunjoon Park and Donghyeon Cho},
            title     = {3DGS에서 2D SAM을 활용할 때 발생하는 한계점 극복 및 효과적인 3차원 공간 이해를 위한 방법에 관한 연구},
            booktitle = {Proceedings of the 38th Workshop on Image Processing and Image Understanding (IPIU)},
            year      = {2026}
          }

      - title: 3DGS를 활용한 Point Cloud 합성 및 3차원 합성 공간 복원에 대한 연구
        authors: <strong style="color:#1a73e8;">Hyunjoon Park</strong>, Donghyeon Cho
        venue: _IPIU 2025_ (37th Workshop on Image Processing and Image Understanding)
        image: images/ipiu25.png
        link: http://www.ipiu.or.kr/
        link_text: Site
        badges:
          - text: Domestic
            type: domestic
          - text: Workshop
            type: workshop
          - text: Poster
            type: poster
        abstract: |
          멀티 뷰 데이터셋으로부터 카메라 매개변수와 객체 위치를 추정하는 novel-view synthesis 기술인 3D Gaussian Splatting (3DGS)은 3차원 공간을 효과적으로 재구성하는 기술로 주목을 받고 있다.
          기존 연구들이 주로 novel-view synthesis에 초점이 맞춰져 있다면 Gaussian grouping에서는 SAM (Segment Anything)을 활용하여 마스크 이미지를 생성하고 이를 이용해 3DGS 학습 이후 3차원 정보에서 특정 객체를 분리할 수 있게 되어 주로 2차원 공간에서 진행이 되었던 영역을 3차원으로 확장을 시켰다는 점에서 의의가 있다.
          따라서 본 연구에서는 Gaussian grouping을 활용하여 3차원 공간에서 객체를 분리하고 이것을 다른 배경에 합성하여 새로운 3차원 공간을 재구성하는 것을 목표로 설정하였고 이를 통해 재구성된 3차원 공간에서의 객체 조작 및 재구성 가능성을 탐색하고 결과를 통해 이러한 접근 방식의 효율성을 검증하고자 한다.
        bibtex: |
          @inproceedings{park2025pointcloud3dgs,
            author    = {Hyunjoon Park and Donghyeon Cho},
            title     = {3DGS를 활용한 Point Cloud 합성 및 3차원 합성 공간 복원에 대한 연구},
            booktitle = {Proceedings of the 37th Workshop on Image Processing and Image Understanding (IPIU)},
            year      = {2025}
          }

  - title: Projects # Title for the section
    layout: card # Type of content section (card layout)
    content:
      - title: Consistent 3D Scene Editing via Semantic Geometric Feature Fields in Gaussian Splatting
        authors: <strong style="color:#1a73e8;">Hyunjoon Park</strong>
        venue: "Advanced Computer Vision (Prof. Soonmin Hwang) | _Mar 2025 - Jun 2025_"
        image: images/ACV_2025.png
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/hjpark83/ACV_2025_Project
        badges:
          - text: Best Reviewer
            type: best
          - text: Oral Presentation
            type: oral
        abstract: |
          This project addresses the view-inconsistency and over-segmentation issues in 3DGS-based editing caused by naive 2D mask lifting.
          We proposed a two-stage refinement pipeline—depth-aware hierarchical merging and cross-view mask matching—integrating DINOv2, LoG edges, and DPT depth.
          Our approach transforms fragmented masks into semantically coherent global objects, enabling stable interactive editing (removal, inpainting) while maintaining high-fidelity rendering.

      - title: Music to Dance Video Generation
        authors: Donghyeon Cho, <strong style="color:#1a73e8;">Hyunjoon Park</strong>, Junha Kim (Hanyang University), Nokap Park (SK Telecom), Sungeun Hong (Sungkyunkwan University)
        venue: "Industry-Academia Collaboration | _Feb 2025 - Present_"
        image: images/grid_wguidance.gif
        abstract: |
          3D Dance Video Generation Aligned with Music from a Single Reference Image.
          This project is a collaboration between Hanyang University, SK Telecom, and Sungkyunkwan University.

      - title: 3D Synthesized Space Reconstruction using 3D Gaussian Splatting
        authors: <strong style="color:#1a73e8;">Hyunjoon Park</strong>, Dohyeon Lim
        venue: "Graduation Project (Supervisor: Prof. Sungyoon Lee) | _Feb 2024 - Nov 2024_"
        image: images/project_result.png
        additional_links:
          - title: Project Page
            icon: fas fa-globe
            url: https://github.com/Capstone-SW-Project
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Capstone-SW-Project/3D-Synthesized-Space-Reconstruction-using-3DGS
        abstract: |
          Synthesize a high-quality point cloud from multi-view images using 3D Gaussian Splatting (3DGS) and reconstruct the 3D synthesized space effectively.
          This project explores the possibilities of object manipulation and reconstruction in reconstructed 3D spaces.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HYU CVLab
        icon: images/cvlab.png
        link: https://sites.google.com/view/hyu-cv
        link_text: hyu-cvlab
        sub_title: Undergraduate Intern
        caption: 2024.7.1 - 2025.8.31
        description: | # this will include new lines to allow paragraphs
            Undergraduate Intern at CVLab, Hanyang University under the supervision of Prof. Donghyeon Cho.
            - Research on 3D Vision especially 3D Gaussian Splatting and 3D Human Reconstruction
            - I've studied various human models such as SMPL, PIFu (Pixel-Aligned Implicit Function), and 3DGS based human reconstruction methods.

  - title: TA Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Creative Computing for Engineers
        icon: images/cce.png
        sub_title: Teaching Assistant
        caption: 2026.3 - 2026.6
        description: | # this will include new lines to allow paragraphs
          - **Course Description** \
            This course is designed to learn the basics of C and Python languages.
            It covers a wide range of topics, including data types, control structures, functions, and libraries in both languages.
            The course emphasizes hands-on programming exercises and projects to reinforce learning and develop practical coding skills.
          - **Responsibilities**
            > Assisting with practical sessions on C and Python programming\
            > Proctoring exams and grading exam questions\        
            > Providing feedback on students' code and helping them improve their programming skills

      - layout: left
        title: Creative Software Programming
        icon: images/cpp.png
        sub_title: Teaching Assistant
        caption: 2025.9 - 2025.12
        description: | # this will include new lines to allow paragraphs
          - **Course Description** \
            This course is designed to foster creativity and problem-solving skills through c++ programming.
            It covers a wide range of topics, including algorithm design, data structures, software development methodologies, and creative coding projects.
            The course encourages students to think outside the box and apply programming concepts to real-world problems in innovative ways.
          - **Responsibilities** \
            > Assisting with lectures for weeks 13-15 and conducting practical sessions on STL (Standard Template Library)\
            > Creating and grading assignments and exam questions\
            > Providing feedback on students' code and helping them improve their programming skills


  # - title: Awards & Honors # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Award Name
  #       sub_title: Organization or Institution
  #       caption: Date
  #       description: | # this will include new lines to allow paragraphs
  #         Description of the award or honor.
  #         - What it was for
  #         - Competition details or selection criteria
  #         - Any notable achievements

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)  
    content:
      - layout : left
        title: Hanyang University
        icon: images/hyu.png
        sub_title: Master's degree
        description: | # this will include new lines to allow paragraphs
          - **Major** \
            Computer Software Engineering
          - **Advisor** \
            Prof. Donghyeon Cho
          - **Graduation (Expected)** \
            Aug 2027
      - layout: left
        title: Hanyang University
        icon: images/hyu.png
        sub_title: Bachelor's degree
        description: | # this will include new lines to allow paragraphs
          - **Major** \
            Computer Software Engineering
          - **Graduation** \
            Aug 2025
      - layout: left
        title: Hwanil High School
        icon: images/hwanil.png
        sub_title: High School Diploma
        description: |
          - **Graduation** \
            Feb 2018

      - layout: left
        title: Ewha Womans University Keumlan Middle School
        icon: images/ewha.png
        sub_title: Middle School Diploma
        description: |
          - **Graduation** \
            Feb 2015

  - title: Languages # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korean
        icon: images/korea.png
        sub_title: Native
        description: | # this will include new lines to allow paragraphs
          Native speaker with full proficiency in reading, writing, speaking, and listening.

      - layout: left
        title: English
        icon: images/english.png
        sub_title: Fluent
        description: | # this will include new lines to allow paragraphs
          - Proficient in academic and professional communication
          - Capable of reading research papers and technical documentation

      - layout: left
        title: Japanese
        icon: images/japan.png
        sub_title: Basic Communication Skills
        description: | # this will include new lines to allow paragraphs
          Basic conversational skills for communication.

  - title: Programs # 참석하거나 활동한 내역
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The AI Korea 2025
        link: https://aisociety.kr/ai-korea-2025/
        link_text: AI Korea 2025
        caption: 2025.8.12 - 2025.8.13
        description: | # this will include new lines to allow paragraphs
          - **Description** \
            한국 정보과학회 인공지능소사이어티 주관 AI 학술대회
          - **Activities** \
            > Session1 : Invited Talk - AI Experts and Emerging Researchers\
            > Session2 : Industry Session\
            > Session3 : Pattern Recognition and Machine Learning\
            > Session4 : AI tutorials
      
      - layout: left
        title: 대한전자공학회 영상처리 여름학교
        icon: images/ieie.png
        link: https://www.theieie.org/events/?part=03&c_id=949
        link_text: 영상처리 여름학교
        caption: 2025.7.18 - 2025.7.18
        description: | # this will include new lines to allow paragraphs
          - **Description** \
            영상이해/영상처리 연구회 합동 여름학교
          - **Activities** \
            > Lectures by Experts and Professors who research in the field of Image Processing and Computer Vision

      - layout: left
        title: LG Aimers 7th
        icon: images/aimers.png
        link: https://lgaimers.ai/
        link_text: LG Aimers
        caption: 2025.7.1 - 2025.8.30
        description: | # this will include new lines to allow paragraphs
          - **Description** \
            LG 주관 AI 교육 프로그램
          - **Activities** \
            > AI Special Lectures by Experts \
            > AI Hackerthon (Team-based) : 식음료 수요량 예측 AI 모델 개발

      - layout: left
        title: LG Aimers 5th
        icon: images/aimers.png
        link: https://lgaimers.ai/
        link_text: LG Aimers
        caption: 2024.7.1 - 2024.8.30
        description: | # this will include new lines to allow paragraphs
          - **Description** \
            LG 주관 AI 교육 프로그램
          - **Activities** \
            > AI Special Lectures by Experts \
            > AI Hackerthon (Team-based) : 이상치 탐지 모델 개발

      - layout: left
        title: NAVER Boostclass
        icon: images/naver.png
        link_text: NAVER AI Boostclass
        caption: 2024.1.15 - 2024.2.27
        description: | # this will include new lines to allow paragraphs
          - **Description** \
            NAVER Boostclass AI 엔지니어 기초 다지기
          - **Activities** \
            > AI Special Lectures by Experts

footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag